language: python

python:
  # - 2.6
  # - 2.7
  - 3.3

services: postgresql

env:
  global:
# - DJANGO="x.y.z"
  - DJANGO_SETTINGS_MODULE="superlists.settings"
  - PYTHONPATH="/home/travis/build/jiso/testing-goat/superlists"
  - PIP_USE_MIRRORS=true
# Last two for OS X, courtesy of stackoverflow.com/a/22697917/419005
# - CFLAGS=-Qunused-arguments
# - CPPFLAGS=-Qunused-arguments

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - python superlists/manage.py syncdb --noinput
  - coverage run --source lists,superlists --branch --omit */migrations/*,*/tests/*,*/functional_tests/* superlists/manage.py test
#  - python superlists/manage.py test
after_success:
  - coveralls
